services:
  backend:
    build: ./backend
    container_name: tapah_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development

  frontend:
    build: ./frontend
    container_name: tapah_frontend
    ports:
      - "1420:1420"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true # Keeps the interactive shell open
    tty: true
    environment:
      - NG_CLI_ANALYTICS=false
      - CHOKIDAR_USEPOLLING=true